/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderApprovalJobIdRouteImport } from './routes/provider.approval.$jobId'
import { Route as ProviderAdjustJobIdRouteImport } from './routes/provider.adjust.$jobId'

const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderApprovalJobIdRoute = ProviderApprovalJobIdRouteImport.update({
  id: '/approval/$jobId',
  path: '/approval/$jobId',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderAdjustJobIdRoute = ProviderAdjustJobIdRouteImport.update({
  id: '/adjust/$jobId',
  path: '/adjust/$jobId',
  getParentRoute: () => ProviderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/estimate': typeof EstimateRoute
  '/provider': typeof ProviderRouteWithChildren
  '/provider/adjust/$jobId': typeof ProviderAdjustJobIdRoute
  '/provider/approval/$jobId': typeof ProviderApprovalJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/estimate': typeof EstimateRoute
  '/provider': typeof ProviderRouteWithChildren
  '/provider/adjust/$jobId': typeof ProviderAdjustJobIdRoute
  '/provider/approval/$jobId': typeof ProviderApprovalJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/estimate': typeof EstimateRoute
  '/provider': typeof ProviderRouteWithChildren
  '/provider/adjust/$jobId': typeof ProviderAdjustJobIdRoute
  '/provider/approval/$jobId': typeof ProviderApprovalJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/estimate'
    | '/provider'
    | '/provider/adjust/$jobId'
    | '/provider/approval/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/estimate'
    | '/provider'
    | '/provider/adjust/$jobId'
    | '/provider/approval/$jobId'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/estimate'
    | '/provider'
    | '/provider/adjust/$jobId'
    | '/provider/approval/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  EstimateRoute: typeof EstimateRoute
  ProviderRoute: typeof ProviderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/approval/$jobId': {
      id: '/provider/approval/$jobId'
      path: '/approval/$jobId'
      fullPath: '/provider/approval/$jobId'
      preLoaderRoute: typeof ProviderApprovalJobIdRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/adjust/$jobId': {
      id: '/provider/adjust/$jobId'
      path: '/adjust/$jobId'
      fullPath: '/provider/adjust/$jobId'
      preLoaderRoute: typeof ProviderAdjustJobIdRouteImport
      parentRoute: typeof ProviderRoute
    }
  }
}

interface ProviderRouteChildren {
  ProviderAdjustJobIdRoute: typeof ProviderAdjustJobIdRoute
  ProviderApprovalJobIdRoute: typeof ProviderApprovalJobIdRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderAdjustJobIdRoute: ProviderAdjustJobIdRoute,
  ProviderApprovalJobIdRoute: ProviderApprovalJobIdRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  EstimateRoute: EstimateRoute,
  ProviderRoute: ProviderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
